// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/lp_rpc.proto

package net

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OSInfo_StorageType int32

const (
	OSInfo_DIRECT OSInfo_StorageType = 0
	OSInfo_S3     OSInfo_StorageType = 1
	OSInfo_GOOGLE OSInfo_StorageType = 2
)

var OSInfo_StorageType_name = map[int32]string{
	0: "DIRECT",
	1: "S3",
	2: "GOOGLE",
}

var OSInfo_StorageType_value = map[string]int32{
	"DIRECT": 0,
	"S3":     1,
	"GOOGLE": 2,
}

func (x OSInfo_StorageType) String() string {
	return proto.EnumName(OSInfo_StorageType_name, int32(x))
}

func (OSInfo_StorageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{4, 0}
}

// Desired output format
type VideoProfile_Format int32

const (
	VideoProfile_MPEGTS VideoProfile_Format = 0
	VideoProfile_MP4    VideoProfile_Format = 1
)

var VideoProfile_Format_name = map[int32]string{
	0: "MPEGTS",
	1: "MP4",
}

var VideoProfile_Format_value = map[string]int32{
	"MPEGTS": 0,
	"MP4":    1,
}

func (x VideoProfile_Format) String() string {
	return proto.EnumName(VideoProfile_Format_name, int32(x))
}

func (VideoProfile_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{12, 0}
}

type VideoProfile_Profile int32

const (
	VideoProfile_ENCODER_DEFAULT       VideoProfile_Profile = 0
	VideoProfile_H264_BASELINE         VideoProfile_Profile = 1
	VideoProfile_H264_MAIN             VideoProfile_Profile = 2
	VideoProfile_H264_HIGH             VideoProfile_Profile = 3
	VideoProfile_H264_CONSTRAINED_HIGH VideoProfile_Profile = 4
)

var VideoProfile_Profile_name = map[int32]string{
	0: "ENCODER_DEFAULT",
	1: "H264_BASELINE",
	2: "H264_MAIN",
	3: "H264_HIGH",
	4: "H264_CONSTRAINED_HIGH",
}

var VideoProfile_Profile_value = map[string]int32{
	"ENCODER_DEFAULT":       0,
	"H264_BASELINE":         1,
	"H264_MAIN":             2,
	"H264_HIGH":             3,
	"H264_CONSTRAINED_HIGH": 4,
}

func (x VideoProfile_Profile) String() string {
	return proto.EnumName(VideoProfile_Profile_name, int32(x))
}

func (VideoProfile_Profile) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{12, 1}
}

type VideoProfile_VideoCodec int32

const (
	VideoProfile_H264 VideoProfile_VideoCodec = 0
	VideoProfile_H265 VideoProfile_VideoCodec = 1
	VideoProfile_VP8  VideoProfile_VideoCodec = 2
	VideoProfile_VP9  VideoProfile_VideoCodec = 3
)

var VideoProfile_VideoCodec_name = map[int32]string{
	0: "H264",
	1: "H265",
	2: "VP8",
	3: "VP9",
}

var VideoProfile_VideoCodec_value = map[string]int32{
	"H264": 0,
	"H265": 1,
	"VP8":  2,
	"VP9":  3,
}

func (x VideoProfile_VideoCodec) String() string {
	return proto.EnumName(VideoProfile_VideoCodec_name, int32(x))
}

func (VideoProfile_VideoCodec) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{12, 2}
}

type VideoProfile_ChromaSubsampling int32

const (
	VideoProfile_CHROMA_420 VideoProfile_ChromaSubsampling = 0
	VideoProfile_CHROMA_422 VideoProfile_ChromaSubsampling = 1
	VideoProfile_CHROMA_444 VideoProfile_ChromaSubsampling = 2
)

var VideoProfile_ChromaSubsampling_name = map[int32]string{
	0: "CHROMA_420",
	1: "CHROMA_422",
	2: "CHROMA_444",
}

var VideoProfile_ChromaSubsampling_value = map[string]int32{
	"CHROMA_420": 0,
	"CHROMA_422": 1,
	"CHROMA_444": 2,
}

func (x VideoProfile_ChromaSubsampling) String() string {
	return proto.EnumName(VideoProfile_ChromaSubsampling_name, int32(x))
}

func (VideoProfile_ChromaSubsampling) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{12, 3}
}

type PingPong struct {
	// Implementation defined
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPong) Reset()         { *m = PingPong{} }
func (m *PingPong) String() string { return proto.CompactTextString(m) }
func (*PingPong) ProtoMessage()    {}
func (*PingPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{0}
}

func (m *PingPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPong.Unmarshal(m, b)
}
func (m *PingPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPong.Marshal(b, m, deterministic)
}
func (m *PingPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPong.Merge(m, src)
}
func (m *PingPong) XXX_Size() int {
	return xxx_messageInfo_PingPong.Size(m)
}
func (m *PingPong) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPong.DiscardUnknown(m)
}

var xxx_messageInfo_PingPong proto.InternalMessageInfo

func (m *PingPong) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// sent by Broadcaster to Orchestrator to terminate the transcoding session and
// free resources (used for verification sessions)
type EndTranscodingSessionRequest struct {
	// Data for transcoding authentication
	AuthToken            *AuthToken `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EndTranscodingSessionRequest) Reset()         { *m = EndTranscodingSessionRequest{} }
func (m *EndTranscodingSessionRequest) String() string { return proto.CompactTextString(m) }
func (*EndTranscodingSessionRequest) ProtoMessage()    {}
func (*EndTranscodingSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{1}
}

func (m *EndTranscodingSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndTranscodingSessionRequest.Unmarshal(m, b)
}
func (m *EndTranscodingSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndTranscodingSessionRequest.Marshal(b, m, deterministic)
}
func (m *EndTranscodingSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndTranscodingSessionRequest.Merge(m, src)
}
func (m *EndTranscodingSessionRequest) XXX_Size() int {
	return xxx_messageInfo_EndTranscodingSessionRequest.Size(m)
}
func (m *EndTranscodingSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndTranscodingSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndTranscodingSessionRequest proto.InternalMessageInfo

func (m *EndTranscodingSessionRequest) GetAuthToken() *AuthToken {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

type EndTranscodingSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndTranscodingSessionResponse) Reset()         { *m = EndTranscodingSessionResponse{} }
func (m *EndTranscodingSessionResponse) String() string { return proto.CompactTextString(m) }
func (*EndTranscodingSessionResponse) ProtoMessage()    {}
func (*EndTranscodingSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{2}
}

func (m *EndTranscodingSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndTranscodingSessionResponse.Unmarshal(m, b)
}
func (m *EndTranscodingSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndTranscodingSessionResponse.Marshal(b, m, deterministic)
}
func (m *EndTranscodingSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndTranscodingSessionResponse.Merge(m, src)
}
func (m *EndTranscodingSessionResponse) XXX_Size() int {
	return xxx_messageInfo_EndTranscodingSessionResponse.Size(m)
}
func (m *EndTranscodingSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndTranscodingSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndTranscodingSessionResponse proto.InternalMessageInfo

// This request is sent by the broadcaster in `GetTranscoder` to request
// information on which transcoder to use.
type OrchestratorRequest struct {
	// Ethereum address of the broadcaster
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Broadcaster's signature over its address
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	// Features and constraints required by the broadcaster
	Capabilities *Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Don't throw error in case of missing capacity, used for refreshing session
	// when we don't need to check capacity
	IgnoreCapacityCheck  bool     `protobuf:"varint,4,opt,name=ignoreCapacityCheck,proto3" json:"ignoreCapacityCheck,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrchestratorRequest) Reset()         { *m = OrchestratorRequest{} }
func (m *OrchestratorRequest) String() string { return proto.CompactTextString(m) }
func (*OrchestratorRequest) ProtoMessage()    {}
func (*OrchestratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{3}
}

func (m *OrchestratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrchestratorRequest.Unmarshal(m, b)
}
func (m *OrchestratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrchestratorRequest.Marshal(b, m, deterministic)
}
func (m *OrchestratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrchestratorRequest.Merge(m, src)
}
func (m *OrchestratorRequest) XXX_Size() int {
	return xxx_messageInfo_OrchestratorRequest.Size(m)
}
func (m *OrchestratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrchestratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrchestratorRequest proto.InternalMessageInfo

func (m *OrchestratorRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OrchestratorRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *OrchestratorRequest) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *OrchestratorRequest) GetIgnoreCapacityCheck() bool {
	if m != nil {
		return m.IgnoreCapacityCheck
	}
	return false
}

// OSInfo needed to negotiate storages that will be used.
// It carries info needed to write to the storage.
type OSInfo struct {
	// Storage type: direct, s3, ipfs.
	StorageType          OSInfo_StorageType `protobuf:"varint,1,opt,name=storageType,proto3,enum=net.OSInfo_StorageType" json:"storageType,omitempty"`
	S3Info               *S3OSInfo          `protobuf:"bytes,16,opt,name=s3info,proto3" json:"s3info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OSInfo) Reset()         { *m = OSInfo{} }
func (m *OSInfo) String() string { return proto.CompactTextString(m) }
func (*OSInfo) ProtoMessage()    {}
func (*OSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{4}
}

func (m *OSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OSInfo.Unmarshal(m, b)
}
func (m *OSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OSInfo.Marshal(b, m, deterministic)
}
func (m *OSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OSInfo.Merge(m, src)
}
func (m *OSInfo) XXX_Size() int {
	return xxx_messageInfo_OSInfo.Size(m)
}
func (m *OSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OSInfo proto.InternalMessageInfo

func (m *OSInfo) GetStorageType() OSInfo_StorageType {
	if m != nil {
		return m.StorageType
	}
	return OSInfo_DIRECT
}

func (m *OSInfo) GetS3Info() *S3OSInfo {
	if m != nil {
		return m.S3Info
	}
	return nil
}

type S3OSInfo struct {
	// Host to use to connect to S3
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Key (prefix) to use when uploading the object.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// POST policy that S3 owner node creates to give write access to other node.
	Policy string `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	// Signature for POST policy.
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Needed for POST policy.
	Credential string `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	// Needed for POST policy.
	XAmzDate             string   `protobuf:"bytes,6,opt,name=xAmzDate,proto3" json:"xAmzDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3OSInfo) Reset()         { *m = S3OSInfo{} }
func (m *S3OSInfo) String() string { return proto.CompactTextString(m) }
func (*S3OSInfo) ProtoMessage()    {}
func (*S3OSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{5}
}

func (m *S3OSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3OSInfo.Unmarshal(m, b)
}
func (m *S3OSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3OSInfo.Marshal(b, m, deterministic)
}
func (m *S3OSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3OSInfo.Merge(m, src)
}
func (m *S3OSInfo) XXX_Size() int {
	return xxx_messageInfo_S3OSInfo.Size(m)
}
func (m *S3OSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S3OSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S3OSInfo proto.InternalMessageInfo

func (m *S3OSInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *S3OSInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *S3OSInfo) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *S3OSInfo) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *S3OSInfo) GetCredential() string {
	if m != nil {
		return m.Credential
	}
	return ""
}

func (m *S3OSInfo) GetXAmzDate() string {
	if m != nil {
		return m.XAmzDate
	}
	return ""
}

// PriceInfo conveys pricing info for transcoding services
type PriceInfo struct {
	// price in wei
	PricePerUnit int64 `protobuf:"varint,1,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	// Pixels covered in the price
	// Set price to 1 wei and pixelsPerUnit > 1 to have a smaller price
	// granularity per pixel than 1 wei
	PixelsPerUnit int64 `protobuf:"varint,2,opt,name=pixelsPerUnit,proto3" json:"pixelsPerUnit,omitempty"`
	// Capability price is for
	Capability uint32 `protobuf:"varint,3,opt,name=capability,proto3" json:"capability,omitempty"`
	// constraint price is for
	Constraint           string   `protobuf:"bytes,4,opt,name=constraint,proto3" json:"constraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceInfo) Reset()         { *m = PriceInfo{} }
func (m *PriceInfo) String() string { return proto.CompactTextString(m) }
func (*PriceInfo) ProtoMessage()    {}
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{6}
}

func (m *PriceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceInfo.Unmarshal(m, b)
}
func (m *PriceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceInfo.Marshal(b, m, deterministic)
}
func (m *PriceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceInfo.Merge(m, src)
}
func (m *PriceInfo) XXX_Size() int {
	return xxx_messageInfo_PriceInfo.Size(m)
}
func (m *PriceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PriceInfo proto.InternalMessageInfo

func (m *PriceInfo) GetPricePerUnit() int64 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *PriceInfo) GetPixelsPerUnit() int64 {
	if m != nil {
		return m.PixelsPerUnit
	}
	return 0
}

func (m *PriceInfo) GetCapability() uint32 {
	if m != nil {
		return m.Capability
	}
	return 0
}

func (m *PriceInfo) GetConstraint() string {
	if m != nil {
		return m.Constraint
	}
	return ""
}

type Capabilities struct {
	// Bit string of supported features - one bit per feature
	Bitstring []uint64 `protobuf:"varint,1,rep,packed,name=bitstring,proto3" json:"bitstring,omitempty"`
	// Bit string of features that are required to be supported
	Mandatories []uint64 `protobuf:"varint,2,rep,packed,name=mandatories,proto3" json:"mandatories,omitempty"`
	// Capacity corresponding to each capability
	Capacities           map[uint32]uint32         `protobuf:"bytes,3,rep,name=capacities,proto3" json:"capacities,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Version              string                    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Constraints          *Capabilities_Constraints `protobuf:"bytes,5,opt,name=constraints,proto3" json:"constraints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Capabilities) Reset()         { *m = Capabilities{} }
func (m *Capabilities) String() string { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()    {}
func (*Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{7}
}

func (m *Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities.Unmarshal(m, b)
}
func (m *Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities.Marshal(b, m, deterministic)
}
func (m *Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities.Merge(m, src)
}
func (m *Capabilities) XXX_Size() int {
	return xxx_messageInfo_Capabilities.Size(m)
}
func (m *Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities proto.InternalMessageInfo

func (m *Capabilities) GetBitstring() []uint64 {
	if m != nil {
		return m.Bitstring
	}
	return nil
}

func (m *Capabilities) GetMandatories() []uint64 {
	if m != nil {
		return m.Mandatories
	}
	return nil
}

func (m *Capabilities) GetCapacities() map[uint32]uint32 {
	if m != nil {
		return m.Capacities
	}
	return nil
}

func (m *Capabilities) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Capabilities) GetConstraints() *Capabilities_Constraints {
	if m != nil {
		return m.Constraints
	}
	return nil
}

// Non-binary constraints.
type Capabilities_Constraints struct {
	MinVersion           string                                         `protobuf:"bytes,1,opt,name=minVersion,proto3" json:"minVersion,omitempty"`
	PerCapability        map[uint32]*Capabilities_CapabilityConstraints `protobuf:"bytes,2,rep,name=PerCapability,proto3" json:"PerCapability,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Capabilities_Constraints) Reset()         { *m = Capabilities_Constraints{} }
func (m *Capabilities_Constraints) String() string { return proto.CompactTextString(m) }
func (*Capabilities_Constraints) ProtoMessage()    {}
func (*Capabilities_Constraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{7, 1}
}

func (m *Capabilities_Constraints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities_Constraints.Unmarshal(m, b)
}
func (m *Capabilities_Constraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities_Constraints.Marshal(b, m, deterministic)
}
func (m *Capabilities_Constraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities_Constraints.Merge(m, src)
}
func (m *Capabilities_Constraints) XXX_Size() int {
	return xxx_messageInfo_Capabilities_Constraints.Size(m)
}
func (m *Capabilities_Constraints) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities_Constraints.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities_Constraints proto.InternalMessageInfo

func (m *Capabilities_Constraints) GetMinVersion() string {
	if m != nil {
		return m.MinVersion
	}
	return ""
}

func (m *Capabilities_Constraints) GetPerCapability() map[uint32]*Capabilities_CapabilityConstraints {
	if m != nil {
		return m.PerCapability
	}
	return nil
}

// Non-binary capability constraints, such as supported ranges.
type Capabilities_CapabilityConstraints struct {
	Models               map[string]*Capabilities_CapabilityConstraints_ModelConstraint `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                       `json:"-"`
	XXX_unrecognized     []byte                                                         `json:"-"`
	XXX_sizecache        int32                                                          `json:"-"`
}

func (m *Capabilities_CapabilityConstraints) Reset()         { *m = Capabilities_CapabilityConstraints{} }
func (m *Capabilities_CapabilityConstraints) String() string { return proto.CompactTextString(m) }
func (*Capabilities_CapabilityConstraints) ProtoMessage()    {}
func (*Capabilities_CapabilityConstraints) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{7, 2}
}

func (m *Capabilities_CapabilityConstraints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities_CapabilityConstraints.Unmarshal(m, b)
}
func (m *Capabilities_CapabilityConstraints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities_CapabilityConstraints.Marshal(b, m, deterministic)
}
func (m *Capabilities_CapabilityConstraints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities_CapabilityConstraints.Merge(m, src)
}
func (m *Capabilities_CapabilityConstraints) XXX_Size() int {
	return xxx_messageInfo_Capabilities_CapabilityConstraints.Size(m)
}
func (m *Capabilities_CapabilityConstraints) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities_CapabilityConstraints.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities_CapabilityConstraints proto.InternalMessageInfo

func (m *Capabilities_CapabilityConstraints) GetModels() map[string]*Capabilities_CapabilityConstraints_ModelConstraint {
	if m != nil {
		return m.Models
	}
	return nil
}

type Capabilities_CapabilityConstraints_ModelConstraint struct {
	Warm                 bool     `protobuf:"varint,1,opt,name=warm,proto3" json:"warm,omitempty"`
	Capacity             uint32   `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RunnerVersion        string   `protobuf:"bytes,3,opt,name=runnerVersion,proto3" json:"runnerVersion,omitempty"`
	CapacityInUse        uint32   `protobuf:"varint,4,opt,name=capacityInUse,proto3" json:"capacityInUse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capabilities_CapabilityConstraints_ModelConstraint) Reset() {
	*m = Capabilities_CapabilityConstraints_ModelConstraint{}
}
func (m *Capabilities_CapabilityConstraints_ModelConstraint) String() string {
	return proto.CompactTextString(m)
}
func (*Capabilities_CapabilityConstraints_ModelConstraint) ProtoMessage() {}
func (*Capabilities_CapabilityConstraints_ModelConstraint) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{7, 2, 0}
}

func (m *Capabilities_CapabilityConstraints_ModelConstraint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities_CapabilityConstraints_ModelConstraint.Unmarshal(m, b)
}
func (m *Capabilities_CapabilityConstraints_ModelConstraint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities_CapabilityConstraints_ModelConstraint.Marshal(b, m, deterministic)
}
func (m *Capabilities_CapabilityConstraints_ModelConstraint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities_CapabilityConstraints_ModelConstraint.Merge(m, src)
}
func (m *Capabilities_CapabilityConstraints_ModelConstraint) XXX_Size() int {
	return xxx_messageInfo_Capabilities_CapabilityConstraints_ModelConstraint.Size(m)
}
func (m *Capabilities_CapabilityConstraints_ModelConstraint) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities_CapabilityConstraints_ModelConstraint.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities_CapabilityConstraints_ModelConstraint proto.InternalMessageInfo

func (m *Capabilities_CapabilityConstraints_ModelConstraint) GetWarm() bool {
	if m != nil {
		return m.Warm
	}
	return false
}

func (m *Capabilities_CapabilityConstraints_ModelConstraint) GetCapacity() uint32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Capabilities_CapabilityConstraints_ModelConstraint) GetRunnerVersion() string {
	if m != nil {
		return m.RunnerVersion
	}
	return ""
}

func (m *Capabilities_CapabilityConstraints_ModelConstraint) GetCapacityInUse() uint32 {
	if m != nil {
		return m.CapacityInUse
	}
	return 0
}

// The orchestrator sends this in response to `GetOrchestrator`, containing
// miscellaneous data related to the job.
type OrchestratorInfo struct {
	// URI of the transcoder to use for submitting segments.
	Transcoder string `protobuf:"bytes,1,opt,name=transcoder,proto3" json:"transcoder,omitempty"`
	// Parameters for probabilistic micropayment tickets
	TicketParams *TicketParams `protobuf:"bytes,2,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// Price Info containing the price per pixel to transcode
	PriceInfo *PriceInfo `protobuf:"bytes,3,opt,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	// ETH address that should sign transcoded results
	Address []byte `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// Features and constraints supported by the orchestrator
	Capabilities *Capabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Data for transcoding authentication
	AuthToken *AuthToken `protobuf:"bytes,6,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// Information on Orchestrator hardware
	Hardware []*HardwareInformation `protobuf:"bytes,7,rep,name=hardware,proto3" json:"hardware,omitempty"`
	// Orchestrator returns info about own input object storage, if it wants it to
	// be used.
	Storage []*OSInfo `protobuf:"bytes,32,rep,name=storage,proto3" json:"storage,omitempty"`
	// prices for capabilities
	CapabilitiesPrices   []*PriceInfo `protobuf:"bytes,33,rep,name=capabilities_prices,json=capabilitiesPrices,proto3" json:"capabilities_prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OrchestratorInfo) Reset()         { *m = OrchestratorInfo{} }
func (m *OrchestratorInfo) String() string { return proto.CompactTextString(m) }
func (*OrchestratorInfo) ProtoMessage()    {}
func (*OrchestratorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{8}
}

func (m *OrchestratorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrchestratorInfo.Unmarshal(m, b)
}
func (m *OrchestratorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrchestratorInfo.Marshal(b, m, deterministic)
}
func (m *OrchestratorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrchestratorInfo.Merge(m, src)
}
func (m *OrchestratorInfo) XXX_Size() int {
	return xxx_messageInfo_OrchestratorInfo.Size(m)
}
func (m *OrchestratorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrchestratorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrchestratorInfo proto.InternalMessageInfo

func (m *OrchestratorInfo) GetTranscoder() string {
	if m != nil {
		return m.Transcoder
	}
	return ""
}

func (m *OrchestratorInfo) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *OrchestratorInfo) GetPriceInfo() *PriceInfo {
	if m != nil {
		return m.PriceInfo
	}
	return nil
}

func (m *OrchestratorInfo) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OrchestratorInfo) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *OrchestratorInfo) GetAuthToken() *AuthToken {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *OrchestratorInfo) GetHardware() []*HardwareInformation {
	if m != nil {
		return m.Hardware
	}
	return nil
}

func (m *OrchestratorInfo) GetStorage() []*OSInfo {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *OrchestratorInfo) GetCapabilitiesPrices() []*PriceInfo {
	if m != nil {
		return m.CapabilitiesPrices
	}
	return nil
}

// Data for transcoding authentication that is included in the OrchestratorInfo
// message during discovery
type AuthToken struct {
	// Record used to authenticate for a transcode session
	// Opaque to the receiver
	Token []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ID of the transcode session that the token is authenticating for
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Timestamp when the token expires
	Expiration           int64    `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{9}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthToken) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AuthToken) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

// Data included by the broadcaster when submitting a segment for transcoding.
type SegData struct {
	// Manifest ID this segment belongs to
	ManifestId []byte `protobuf:"bytes,1,opt,name=manifestId,proto3" json:"manifestId,omitempty"`
	// Sequence number of the segment to be transcoded
	Seq int64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Hash of the segment data to be transcoded
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// Transcoding profiles to use
	Profiles []byte `protobuf:"bytes,4,opt,name=profiles,proto3" json:"profiles,omitempty"`
	// Broadcaster signature for the segment. Corresponds to:
	// broadcaster.sign(manifestId | seqNo | dataHash | profiles)
	Sig []byte `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	// Duration of the segment to be transcoded, in milliseconds
	Duration int32 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// Capabilities used by this segment.
	Capabilities *Capabilities `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Data for transcoding authentication
	AuthToken *AuthToken `protobuf:"bytes,8,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// Calculate perceptual hash for this segment
	CalcPerceptualHash bool `protobuf:"varint,10,opt,name=calc_perceptual_hash,json=calcPerceptualHash,proto3" json:"calc_perceptual_hash,omitempty"`
	// Broadcaster's preferred storage medium(s)
	// XXX should we include this in a sig somewhere until certs are
	// authenticated?
	Storage []*OSInfo `protobuf:"bytes,32,rep,name=storage,proto3" json:"storage,omitempty"`
	// Transcoding profiles to use. Supersedes `profiles` field
	// Deprecated by `fullProfiles2` but may still be used for mpegts formats
	FullProfiles []*VideoProfile `protobuf:"bytes,33,rep,name=fullProfiles,proto3" json:"fullProfiles,omitempty"`
	// Transcoding profiles to use. Supersedes `fullProfiles` field
	// Deprecated by `fullProfiles3` but may still be used for integer FPS
	FullProfiles2 []*VideoProfile `protobuf:"bytes,34,rep,name=fullProfiles2,proto3" json:"fullProfiles2,omitempty"`
	// Transcoding profiles to use. Supersedes `fullProfiles2` field
	FullProfiles3 []*VideoProfile `protobuf:"bytes,35,rep,name=fullProfiles3,proto3" json:"fullProfiles3,omitempty"`
	// Transcoding parameters specific to this segment
	SegmentParameters *SegParameters `protobuf:"bytes,37,opt,name=segment_parameters,json=segmentParameters,proto3" json:"segment_parameters,omitempty"`
	// Force HW Session Reinit
	ForceSessionReinit   bool     `protobuf:"varint,38,opt,name=ForceSessionReinit,proto3" json:"ForceSessionReinit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegData) Reset()         { *m = SegData{} }
func (m *SegData) String() string { return proto.CompactTextString(m) }
func (*SegData) ProtoMessage()    {}
func (*SegData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{10}
}

func (m *SegData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegData.Unmarshal(m, b)
}
func (m *SegData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegData.Marshal(b, m, deterministic)
}
func (m *SegData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegData.Merge(m, src)
}
func (m *SegData) XXX_Size() int {
	return xxx_messageInfo_SegData.Size(m)
}
func (m *SegData) XXX_DiscardUnknown() {
	xxx_messageInfo_SegData.DiscardUnknown(m)
}

var xxx_messageInfo_SegData proto.InternalMessageInfo

func (m *SegData) GetManifestId() []byte {
	if m != nil {
		return m.ManifestId
	}
	return nil
}

func (m *SegData) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SegData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SegData) GetProfiles() []byte {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *SegData) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SegData) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *SegData) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *SegData) GetAuthToken() *AuthToken {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

func (m *SegData) GetCalcPerceptualHash() bool {
	if m != nil {
		return m.CalcPerceptualHash
	}
	return false
}

func (m *SegData) GetStorage() []*OSInfo {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *SegData) GetFullProfiles() []*VideoProfile {
	if m != nil {
		return m.FullProfiles
	}
	return nil
}

func (m *SegData) GetFullProfiles2() []*VideoProfile {
	if m != nil {
		return m.FullProfiles2
	}
	return nil
}

func (m *SegData) GetFullProfiles3() []*VideoProfile {
	if m != nil {
		return m.FullProfiles3
	}
	return nil
}

func (m *SegData) GetSegmentParameters() *SegParameters {
	if m != nil {
		return m.SegmentParameters
	}
	return nil
}

func (m *SegData) GetForceSessionReinit() bool {
	if m != nil {
		return m.ForceSessionReinit
	}
	return false
}

type SegParameters struct {
	// Start timestamp from which to start encoding
	// Milliseconds, from start of the file
	From uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// Skip all frames after that timestamp
	// Milliseconds, from start of the file
	To                   uint64   `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegParameters) Reset()         { *m = SegParameters{} }
func (m *SegParameters) String() string { return proto.CompactTextString(m) }
func (*SegParameters) ProtoMessage()    {}
func (*SegParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{11}
}

func (m *SegParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegParameters.Unmarshal(m, b)
}
func (m *SegParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegParameters.Marshal(b, m, deterministic)
}
func (m *SegParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegParameters.Merge(m, src)
}
func (m *SegParameters) XXX_Size() int {
	return xxx_messageInfo_SegParameters.Size(m)
}
func (m *SegParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_SegParameters.DiscardUnknown(m)
}

var xxx_messageInfo_SegParameters proto.InternalMessageInfo

func (m *SegParameters) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SegParameters) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

type VideoProfile struct {
	// Name of VideoProfile
	Name string `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	// Width of VideoProfile
	Width int32 `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	// Height of VideoProfile
	Height int32 `protobuf:"varint,18,opt,name=height,proto3" json:"height,omitempty"`
	// Bitrate of VideoProfile
	Bitrate int32 `protobuf:"varint,19,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// FPS of VideoProfile
	Fps    uint32              `protobuf:"varint,20,opt,name=fps,proto3" json:"fps,omitempty"`
	Format VideoProfile_Format `protobuf:"varint,21,opt,name=format,proto3,enum=net.VideoProfile_Format" json:"format,omitempty"`
	// FPS Denominator of VideoProfile
	FpsDen uint32 `protobuf:"varint,22,opt,name=fpsDen,proto3" json:"fpsDen,omitempty"`
	// Desired codec profile
	Profile VideoProfile_Profile `protobuf:"varint,23,opt,name=profile,proto3,enum=net.VideoProfile_Profile" json:"profile,omitempty"`
	// GOP interval
	Gop int32 `protobuf:"varint,24,opt,name=gop,proto3" json:"gop,omitempty"`
	// Encoder (video codec)
	Encoder              VideoProfile_VideoCodec        `protobuf:"varint,25,opt,name=encoder,proto3,enum=net.VideoProfile_VideoCodec" json:"encoder,omitempty"`
	ColorDepth           int32                          `protobuf:"varint,26,opt,name=colorDepth,proto3" json:"colorDepth,omitempty"`
	ChromaFormat         VideoProfile_ChromaSubsampling `protobuf:"varint,27,opt,name=chromaFormat,proto3,enum=net.VideoProfile_ChromaSubsampling" json:"chromaFormat,omitempty"`
	Quality              uint32                         `protobuf:"varint,28,opt,name=quality,proto3" json:"quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VideoProfile) Reset()         { *m = VideoProfile{} }
func (m *VideoProfile) String() string { return proto.CompactTextString(m) }
func (*VideoProfile) ProtoMessage()    {}
func (*VideoProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{12}
}

func (m *VideoProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoProfile.Unmarshal(m, b)
}
func (m *VideoProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoProfile.Marshal(b, m, deterministic)
}
func (m *VideoProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoProfile.Merge(m, src)
}
func (m *VideoProfile) XXX_Size() int {
	return xxx_messageInfo_VideoProfile.Size(m)
}
func (m *VideoProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoProfile.DiscardUnknown(m)
}

var xxx_messageInfo_VideoProfile proto.InternalMessageInfo

func (m *VideoProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VideoProfile) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *VideoProfile) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VideoProfile) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *VideoProfile) GetFps() uint32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *VideoProfile) GetFormat() VideoProfile_Format {
	if m != nil {
		return m.Format
	}
	return VideoProfile_MPEGTS
}

func (m *VideoProfile) GetFpsDen() uint32 {
	if m != nil {
		return m.FpsDen
	}
	return 0
}

func (m *VideoProfile) GetProfile() VideoProfile_Profile {
	if m != nil {
		return m.Profile
	}
	return VideoProfile_ENCODER_DEFAULT
}

func (m *VideoProfile) GetGop() int32 {
	if m != nil {
		return m.Gop
	}
	return 0
}

func (m *VideoProfile) GetEncoder() VideoProfile_VideoCodec {
	if m != nil {
		return m.Encoder
	}
	return VideoProfile_H264
}

func (m *VideoProfile) GetColorDepth() int32 {
	if m != nil {
		return m.ColorDepth
	}
	return 0
}

func (m *VideoProfile) GetChromaFormat() VideoProfile_ChromaSubsampling {
	if m != nil {
		return m.ChromaFormat
	}
	return VideoProfile_CHROMA_420
}

func (m *VideoProfile) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

// Individual transcoded segment data.
type TranscodedSegmentData struct {
	// URL where the transcoded data can be downloaded from.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Amount of pixels processed (output pixels)
	Pixels int64 `protobuf:"varint,2,opt,name=pixels,proto3" json:"pixels,omitempty"`
	// URL where the perceptual hash data can be downloaded from (can be empty)
	PerceptualHashUrl    string   `protobuf:"bytes,3,opt,name=perceptual_hash_url,json=perceptualHashUrl,proto3" json:"perceptual_hash_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscodedSegmentData) Reset()         { *m = TranscodedSegmentData{} }
func (m *TranscodedSegmentData) String() string { return proto.CompactTextString(m) }
func (*TranscodedSegmentData) ProtoMessage()    {}
func (*TranscodedSegmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{13}
}

func (m *TranscodedSegmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodedSegmentData.Unmarshal(m, b)
}
func (m *TranscodedSegmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodedSegmentData.Marshal(b, m, deterministic)
}
func (m *TranscodedSegmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodedSegmentData.Merge(m, src)
}
func (m *TranscodedSegmentData) XXX_Size() int {
	return xxx_messageInfo_TranscodedSegmentData.Size(m)
}
func (m *TranscodedSegmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodedSegmentData.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodedSegmentData proto.InternalMessageInfo

func (m *TranscodedSegmentData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TranscodedSegmentData) GetPixels() int64 {
	if m != nil {
		return m.Pixels
	}
	return 0
}

func (m *TranscodedSegmentData) GetPerceptualHashUrl() string {
	if m != nil {
		return m.PerceptualHashUrl
	}
	return ""
}

// A set of transcoded segments following the profiles specified in the job.
type TranscodeData struct {
	// Transcoded data, in the order specified in the job options
	Segments []*TranscodedSegmentData `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	// Signature of the hash of the concatenated hashes
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscodeData) Reset()         { *m = TranscodeData{} }
func (m *TranscodeData) String() string { return proto.CompactTextString(m) }
func (*TranscodeData) ProtoMessage()    {}
func (*TranscodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{14}
}

func (m *TranscodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodeData.Unmarshal(m, b)
}
func (m *TranscodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodeData.Marshal(b, m, deterministic)
}
func (m *TranscodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodeData.Merge(m, src)
}
func (m *TranscodeData) XXX_Size() int {
	return xxx_messageInfo_TranscodeData.Size(m)
}
func (m *TranscodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodeData.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodeData proto.InternalMessageInfo

func (m *TranscodeData) GetSegments() []*TranscodedSegmentData {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *TranscodeData) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// Response that a transcoder sends after transcoding a segment.
type TranscodeResult struct {
	// Sequence number of the transcoded results.
	Seq int64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Result of transcoding can be an error, or successful with more info
	//
	// Types that are valid to be assigned to Result:
	//
	//	*TranscodeResult_Error
	//	*TranscodeResult_Data
	Result isTranscodeResult_Result `protobuf_oneof:"result"`
	// Used to notify a broadcaster of updated orchestrator information
	Info                 *OrchestratorInfo `protobuf:"bytes,16,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TranscodeResult) Reset()         { *m = TranscodeResult{} }
func (m *TranscodeResult) String() string { return proto.CompactTextString(m) }
func (*TranscodeResult) ProtoMessage()    {}
func (*TranscodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{15}
}

func (m *TranscodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodeResult.Unmarshal(m, b)
}
func (m *TranscodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodeResult.Marshal(b, m, deterministic)
}
func (m *TranscodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodeResult.Merge(m, src)
}
func (m *TranscodeResult) XXX_Size() int {
	return xxx_messageInfo_TranscodeResult.Size(m)
}
func (m *TranscodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodeResult proto.InternalMessageInfo

func (m *TranscodeResult) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type isTranscodeResult_Result interface {
	isTranscodeResult_Result()
}

type TranscodeResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type TranscodeResult_Data struct {
	Data *TranscodeData `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

func (*TranscodeResult_Error) isTranscodeResult_Result() {}

func (*TranscodeResult_Data) isTranscodeResult_Result() {}

func (m *TranscodeResult) GetResult() isTranscodeResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TranscodeResult) GetError() string {
	if x, ok := m.GetResult().(*TranscodeResult_Error); ok {
		return x.Error
	}
	return ""
}

func (m *TranscodeResult) GetData() *TranscodeData {
	if x, ok := m.GetResult().(*TranscodeResult_Data); ok {
		return x.Data
	}
	return nil
}

func (m *TranscodeResult) GetInfo() *OrchestratorInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TranscodeResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TranscodeResult_Error)(nil),
		(*TranscodeResult_Data)(nil),
	}
}

// Response that an orchestrator sends after processing a payment.
type PaymentResult struct {
	// Used to notify a broadcaster of updated orchestrator information
	Info                 *OrchestratorInfo `protobuf:"bytes,16,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PaymentResult) Reset()         { *m = PaymentResult{} }
func (m *PaymentResult) String() string { return proto.CompactTextString(m) }
func (*PaymentResult) ProtoMessage()    {}
func (*PaymentResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{16}
}

func (m *PaymentResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResult.Unmarshal(m, b)
}
func (m *PaymentResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResult.Marshal(b, m, deterministic)
}
func (m *PaymentResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResult.Merge(m, src)
}
func (m *PaymentResult) XXX_Size() int {
	return xxx_messageInfo_PaymentResult.Size(m)
}
func (m *PaymentResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResult.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResult proto.InternalMessageInfo

func (m *PaymentResult) GetInfo() *OrchestratorInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// Sent by the transcoder to register itself to the orchestrator.
type RegisterRequest struct {
	// Shared secret for auth
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Transcoder capacity
	Capacity int64 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Transcoder capabilities
	Capabilities         *Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{17}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *RegisterRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *RegisterRequest) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// Sent by the orchestrator to the transcoder
type NotifySegment struct {
	// URL of the segment to transcode.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Configuration for the transcoding job
	SegData *SegData `protobuf:"bytes,3,opt,name=segData,proto3" json:"segData,omitempty"`
	// ID for this particular transcoding task.
	TaskId int64 `protobuf:"varint,16,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// Orchestrator identifier for segment metadata
	OrchId string `protobuf:"bytes,18,opt,name=orchId,proto3" json:"orchId,omitempty"`
	// Deprecated by fullProfiles. Set of presets to transcode into.
	// Should be set to an invalid value to induce failures
	Profiles             []byte   `protobuf:"bytes,17,opt,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifySegment) Reset()         { *m = NotifySegment{} }
func (m *NotifySegment) String() string { return proto.CompactTextString(m) }
func (*NotifySegment) ProtoMessage()    {}
func (*NotifySegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{18}
}

func (m *NotifySegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifySegment.Unmarshal(m, b)
}
func (m *NotifySegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifySegment.Marshal(b, m, deterministic)
}
func (m *NotifySegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifySegment.Merge(m, src)
}
func (m *NotifySegment) XXX_Size() int {
	return xxx_messageInfo_NotifySegment.Size(m)
}
func (m *NotifySegment) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifySegment.DiscardUnknown(m)
}

var xxx_messageInfo_NotifySegment proto.InternalMessageInfo

func (m *NotifySegment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *NotifySegment) GetSegData() *SegData {
	if m != nil {
		return m.SegData
	}
	return nil
}

func (m *NotifySegment) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *NotifySegment) GetOrchId() string {
	if m != nil {
		return m.OrchId
	}
	return ""
}

func (m *NotifySegment) GetProfiles() []byte {
	if m != nil {
		return m.Profiles
	}
	return nil
}

// Sent by the aiworker to register itself to the orchestrator.
type RegisterAIWorkerRequest struct {
	// Shared secret for auth
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// AIWorker capabilities
	Capabilities *Capabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// AIWorker hardware info
	Hardware []*HardwareInformation `protobuf:"bytes,3,rep,name=hardware,proto3" json:"hardware,omitempty"`
	// Worker capacity
	Capacity             int64    `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAIWorkerRequest) Reset()         { *m = RegisterAIWorkerRequest{} }
func (m *RegisterAIWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAIWorkerRequest) ProtoMessage()    {}
func (*RegisterAIWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{19}
}

func (m *RegisterAIWorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAIWorkerRequest.Unmarshal(m, b)
}
func (m *RegisterAIWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAIWorkerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAIWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAIWorkerRequest.Merge(m, src)
}
func (m *RegisterAIWorkerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAIWorkerRequest.Size(m)
}
func (m *RegisterAIWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAIWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAIWorkerRequest proto.InternalMessageInfo

func (m *RegisterAIWorkerRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *RegisterAIWorkerRequest) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *RegisterAIWorkerRequest) GetHardware() []*HardwareInformation {
	if m != nil {
		return m.Hardware
	}
	return nil
}

func (m *RegisterAIWorkerRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

// Data included by the gateway when submitting a AI job.
type AIJobData struct {
	// pipeline to use for the job
	Pipeline string `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// AI job request data
	RequestData          []byte   `protobuf:"bytes,2,opt,name=requestData,proto3" json:"requestData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AIJobData) Reset()         { *m = AIJobData{} }
func (m *AIJobData) String() string { return proto.CompactTextString(m) }
func (*AIJobData) ProtoMessage()    {}
func (*AIJobData) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{20}
}

func (m *AIJobData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AIJobData.Unmarshal(m, b)
}
func (m *AIJobData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AIJobData.Marshal(b, m, deterministic)
}
func (m *AIJobData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AIJobData.Merge(m, src)
}
func (m *AIJobData) XXX_Size() int {
	return xxx_messageInfo_AIJobData.Size(m)
}
func (m *AIJobData) XXX_DiscardUnknown() {
	xxx_messageInfo_AIJobData.DiscardUnknown(m)
}

var xxx_messageInfo_AIJobData proto.InternalMessageInfo

func (m *AIJobData) GetPipeline() string {
	if m != nil {
		return m.Pipeline
	}
	return ""
}

func (m *AIJobData) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

// Sent by the orchestrator to the aiworker
type NotifyAIJob struct {
	// Configuration for the AI job
	AIJobData *AIJobData `protobuf:"bytes,1,opt,name=AIJobData,proto3" json:"AIJobData,omitempty"`
	// ID for this particular AI task.
	TaskId               int64    `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyAIJob) Reset()         { *m = NotifyAIJob{} }
func (m *NotifyAIJob) String() string { return proto.CompactTextString(m) }
func (*NotifyAIJob) ProtoMessage()    {}
func (*NotifyAIJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{21}
}

func (m *NotifyAIJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAIJob.Unmarshal(m, b)
}
func (m *NotifyAIJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAIJob.Marshal(b, m, deterministic)
}
func (m *NotifyAIJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAIJob.Merge(m, src)
}
func (m *NotifyAIJob) XXX_Size() int {
	return xxx_messageInfo_NotifyAIJob.Size(m)
}
func (m *NotifyAIJob) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAIJob.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAIJob proto.InternalMessageInfo

func (m *NotifyAIJob) GetAIJobData() *AIJobData {
	if m != nil {
		return m.AIJobData
	}
	return nil
}

func (m *NotifyAIJob) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

// Required parameters for probabilistic micropayment tickets
type TicketParams struct {
	// ETH address of the recipient
	Recipient []byte `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Pay out (in Wei) to the recipient if the ticket wins
	FaceValue []byte `protobuf:"bytes,2,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Probability that the ticket wins
	WinProb []byte `protobuf:"bytes,3,opt,name=win_prob,json=winProb,proto3" json:"win_prob,omitempty"`
	// 32 byte keccak-256 hash commitment to a random number provided
	// by the recipient
	RecipientRandHash []byte `protobuf:"bytes,4,opt,name=recipient_rand_hash,json=recipientRandHash,proto3" json:"recipient_rand_hash,omitempty"`
	// Value generated by recipient that the recipient can use
	// to derive the random number corresponding to the recipient's hash
	// commitment
	Seed []byte `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	// Block number at which the current set of advertised TicketParams is no
	// longer valid
	ExpirationBlock []byte `protobuf:"bytes,6,opt,name=expiration_block,json=expirationBlock,proto3" json:"expiration_block,omitempty"`
	// Expected ticket expiration params
	ExpirationParams     *TicketExpirationParams `protobuf:"bytes,7,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TicketParams) Reset()         { *m = TicketParams{} }
func (m *TicketParams) String() string { return proto.CompactTextString(m) }
func (*TicketParams) ProtoMessage()    {}
func (*TicketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{22}
}

func (m *TicketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketParams.Unmarshal(m, b)
}
func (m *TicketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketParams.Marshal(b, m, deterministic)
}
func (m *TicketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketParams.Merge(m, src)
}
func (m *TicketParams) XXX_Size() int {
	return xxx_messageInfo_TicketParams.Size(m)
}
func (m *TicketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketParams proto.InternalMessageInfo

func (m *TicketParams) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *TicketParams) GetFaceValue() []byte {
	if m != nil {
		return m.FaceValue
	}
	return nil
}

func (m *TicketParams) GetWinProb() []byte {
	if m != nil {
		return m.WinProb
	}
	return nil
}

func (m *TicketParams) GetRecipientRandHash() []byte {
	if m != nil {
		return m.RecipientRandHash
	}
	return nil
}

func (m *TicketParams) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *TicketParams) GetExpirationBlock() []byte {
	if m != nil {
		return m.ExpirationBlock
	}
	return nil
}

func (m *TicketParams) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

// Sender Params (nonces and signatures)
type TicketSenderParams struct {
	// Monotonically increasing counter that makes the ticket
	// unique relative to a particular hash commitment to a recipient's random
	// number
	SenderNonce uint32 `protobuf:"varint,1,opt,name=sender_nonce,json=senderNonce,proto3" json:"sender_nonce,omitempty"`
	// Sender signature over the ticket
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketSenderParams) Reset()         { *m = TicketSenderParams{} }
func (m *TicketSenderParams) String() string { return proto.CompactTextString(m) }
func (*TicketSenderParams) ProtoMessage()    {}
func (*TicketSenderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{23}
}

func (m *TicketSenderParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketSenderParams.Unmarshal(m, b)
}
func (m *TicketSenderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketSenderParams.Marshal(b, m, deterministic)
}
func (m *TicketSenderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketSenderParams.Merge(m, src)
}
func (m *TicketSenderParams) XXX_Size() int {
	return xxx_messageInfo_TicketSenderParams.Size(m)
}
func (m *TicketSenderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketSenderParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketSenderParams proto.InternalMessageInfo

func (m *TicketSenderParams) GetSenderNonce() uint32 {
	if m != nil {
		return m.SenderNonce
	}
	return 0
}

func (m *TicketSenderParams) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// Ticket params for expiration related validation
type TicketExpirationParams struct {
	// Round during which tickets are created
	CreationRound int64 `protobuf:"varint,1,opt,name=creation_round,json=creationRound,proto3" json:"creation_round,omitempty"`
	// Block hash associated with creation_round
	CreationRoundBlockHash []byte   `protobuf:"bytes,2,opt,name=creation_round_block_hash,json=creationRoundBlockHash,proto3" json:"creation_round_block_hash,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TicketExpirationParams) Reset()         { *m = TicketExpirationParams{} }
func (m *TicketExpirationParams) String() string { return proto.CompactTextString(m) }
func (*TicketExpirationParams) ProtoMessage()    {}
func (*TicketExpirationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{24}
}

func (m *TicketExpirationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketExpirationParams.Unmarshal(m, b)
}
func (m *TicketExpirationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketExpirationParams.Marshal(b, m, deterministic)
}
func (m *TicketExpirationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketExpirationParams.Merge(m, src)
}
func (m *TicketExpirationParams) XXX_Size() int {
	return xxx_messageInfo_TicketExpirationParams.Size(m)
}
func (m *TicketExpirationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketExpirationParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketExpirationParams proto.InternalMessageInfo

func (m *TicketExpirationParams) GetCreationRound() int64 {
	if m != nil {
		return m.CreationRound
	}
	return 0
}

func (m *TicketExpirationParams) GetCreationRoundBlockHash() []byte {
	if m != nil {
		return m.CreationRoundBlockHash
	}
	return nil
}

// Payment for transcoding video segments
// A payment can constitute of multiple tickets
// A broadcaster might need to send multiple tickets to top up his credit with
// an Orchestrator
type Payment struct {
	// Probabilistic micropayment ticket parameters
	// These remain the same even when sending multiple tickets
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// ETH address of the sender
	Sender []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Ticket params for expiration related validation
	ExpirationParams   *TicketExpirationParams `protobuf:"bytes,3,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	TicketSenderParams []*TicketSenderParams   `protobuf:"bytes,4,rep,name=ticket_sender_params,json=ticketSenderParams,proto3" json:"ticket_sender_params,omitempty"`
	// O's last known price
	ExpectedPrice        *PriceInfo `protobuf:"bytes,5,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{25}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *Payment) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Payment) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

func (m *Payment) GetTicketSenderParams() []*TicketSenderParams {
	if m != nil {
		return m.TicketSenderParams
	}
	return nil
}

func (m *Payment) GetExpectedPrice() *PriceInfo {
	if m != nil {
		return m.ExpectedPrice
	}
	return nil
}

// GPU information used by worker on network
type GPUComputeInfo struct {
	// unique id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// gpu name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// compute version supported - major
	Major uint32 `protobuf:"varint,4,opt,name=major,proto3" json:"major,omitempty"`
	// compute version supported - minor
	Minor uint32 `protobuf:"varint,5,opt,name=minor,proto3" json:"minor,omitempty"`
	// GPU memory free
	MemoryFree int64 `protobuf:"varint,6,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	// GPU memory total
	MemoryTotal          int64    `protobuf:"varint,7,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPUComputeInfo) Reset()         { *m = GPUComputeInfo{} }
func (m *GPUComputeInfo) String() string { return proto.CompactTextString(m) }
func (*GPUComputeInfo) ProtoMessage()    {}
func (*GPUComputeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{26}
}

func (m *GPUComputeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUComputeInfo.Unmarshal(m, b)
}
func (m *GPUComputeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUComputeInfo.Marshal(b, m, deterministic)
}
func (m *GPUComputeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUComputeInfo.Merge(m, src)
}
func (m *GPUComputeInfo) XXX_Size() int {
	return xxx_messageInfo_GPUComputeInfo.Size(m)
}
func (m *GPUComputeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUComputeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GPUComputeInfo proto.InternalMessageInfo

func (m *GPUComputeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GPUComputeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GPUComputeInfo) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *GPUComputeInfo) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *GPUComputeInfo) GetMemoryFree() int64 {
	if m != nil {
		return m.MemoryFree
	}
	return 0
}

func (m *GPUComputeInfo) GetMemoryTotal() int64 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

// Hardware information for worker on network
type HardwareInformation struct {
	// pipeline hardware supports
	Pipeline string `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// model_id hardware supports
	ModelId string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// hardware for pipeline and model_id
	GpuInfo              map[string]*GPUComputeInfo `protobuf:"bytes,3,rep,name=gpu_info,json=gpuInfo,proto3" json:"gpu_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *HardwareInformation) Reset()         { *m = HardwareInformation{} }
func (m *HardwareInformation) String() string { return proto.CompactTextString(m) }
func (*HardwareInformation) ProtoMessage()    {}
func (*HardwareInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_034e29c79f9ba827, []int{27}
}

func (m *HardwareInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareInformation.Unmarshal(m, b)
}
func (m *HardwareInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareInformation.Marshal(b, m, deterministic)
}
func (m *HardwareInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareInformation.Merge(m, src)
}
func (m *HardwareInformation) XXX_Size() int {
	return xxx_messageInfo_HardwareInformation.Size(m)
}
func (m *HardwareInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareInformation.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareInformation proto.InternalMessageInfo

func (m *HardwareInformation) GetPipeline() string {
	if m != nil {
		return m.Pipeline
	}
	return ""
}

func (m *HardwareInformation) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *HardwareInformation) GetGpuInfo() map[string]*GPUComputeInfo {
	if m != nil {
		return m.GpuInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("net.OSInfo_StorageType", OSInfo_StorageType_name, OSInfo_StorageType_value)
	proto.RegisterEnum("net.VideoProfile_Format", VideoProfile_Format_name, VideoProfile_Format_value)
	proto.RegisterEnum("net.VideoProfile_Profile", VideoProfile_Profile_name, VideoProfile_Profile_value)
	proto.RegisterEnum("net.VideoProfile_VideoCodec", VideoProfile_VideoCodec_name, VideoProfile_VideoCodec_value)
	proto.RegisterEnum("net.VideoProfile_ChromaSubsampling", VideoProfile_ChromaSubsampling_name, VideoProfile_ChromaSubsampling_value)
	proto.RegisterType((*PingPong)(nil), "net.PingPong")
	proto.RegisterType((*EndTranscodingSessionRequest)(nil), "net.EndTranscodingSessionRequest")
	proto.RegisterType((*EndTranscodingSessionResponse)(nil), "net.EndTranscodingSessionResponse")
	proto.RegisterType((*OrchestratorRequest)(nil), "net.OrchestratorRequest")
	proto.RegisterType((*OSInfo)(nil), "net.OSInfo")
	proto.RegisterType((*S3OSInfo)(nil), "net.S3OSInfo")
	proto.RegisterType((*PriceInfo)(nil), "net.PriceInfo")
	proto.RegisterType((*Capabilities)(nil), "net.Capabilities")
	proto.RegisterMapType((map[uint32]uint32)(nil), "net.Capabilities.CapacitiesEntry")
	proto.RegisterType((*Capabilities_Constraints)(nil), "net.Capabilities.Constraints")
	proto.RegisterMapType((map[uint32]*Capabilities_CapabilityConstraints)(nil), "net.Capabilities.Constraints.PerCapabilityEntry")
	proto.RegisterType((*Capabilities_CapabilityConstraints)(nil), "net.Capabilities.CapabilityConstraints")
	proto.RegisterMapType((map[string]*Capabilities_CapabilityConstraints_ModelConstraint)(nil), "net.Capabilities.CapabilityConstraints.ModelsEntry")
	proto.RegisterType((*Capabilities_CapabilityConstraints_ModelConstraint)(nil), "net.Capabilities.CapabilityConstraints.ModelConstraint")
	proto.RegisterType((*OrchestratorInfo)(nil), "net.OrchestratorInfo")
	proto.RegisterType((*AuthToken)(nil), "net.AuthToken")
	proto.RegisterType((*SegData)(nil), "net.SegData")
	proto.RegisterType((*SegParameters)(nil), "net.SegParameters")
	proto.RegisterType((*VideoProfile)(nil), "net.VideoProfile")
	proto.RegisterType((*TranscodedSegmentData)(nil), "net.TranscodedSegmentData")
	proto.RegisterType((*TranscodeData)(nil), "net.TranscodeData")
	proto.RegisterType((*TranscodeResult)(nil), "net.TranscodeResult")
	proto.RegisterType((*PaymentResult)(nil), "net.PaymentResult")
	proto.RegisterType((*RegisterRequest)(nil), "net.RegisterRequest")
	proto.RegisterType((*NotifySegment)(nil), "net.NotifySegment")
	proto.RegisterType((*RegisterAIWorkerRequest)(nil), "net.RegisterAIWorkerRequest")
	proto.RegisterType((*AIJobData)(nil), "net.AIJobData")
	proto.RegisterType((*NotifyAIJob)(nil), "net.NotifyAIJob")
	proto.RegisterType((*TicketParams)(nil), "net.TicketParams")
	proto.RegisterType((*TicketSenderParams)(nil), "net.TicketSenderParams")
	proto.RegisterType((*TicketExpirationParams)(nil), "net.TicketExpirationParams")
	proto.RegisterType((*Payment)(nil), "net.Payment")
	proto.RegisterType((*GPUComputeInfo)(nil), "net.GPUComputeInfo")
	proto.RegisterType((*HardwareInformation)(nil), "net.HardwareInformation")
	proto.RegisterMapType((map[string]*GPUComputeInfo)(nil), "net.HardwareInformation.GpuInfoEntry")
}

func init() {
	proto.RegisterFile("net/lp_rpc.proto", fileDescriptor_034e29c79f9ba827)
}

var fileDescriptor_034e29c79f9ba827 = []byte{
	// 2433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x59, 0xcd, 0x72, 0x1b, 0xc7,
	0x11, 0xd6, 0x02, 0x20, 0x7e, 0x1a, 0x00, 0xb9, 0x1c, 0xea, 0x67, 0x05, 0x4b, 0xb6, 0xb4, 0xb6,
	0x1c, 0xb9, 0x2a, 0xa6, 0x55, 0xa0, 0x24, 0xff, 0x54, 0xb9, 0x6c, 0x8a, 0xa4, 0x48, 0x38, 0x26,
	0x89, 0x1a, 0x50, 0x4a, 0x25, 0x87, 0x20, 0xcb, 0xdd, 0x01, 0xb0, 0x26, 0xb0, 0xbb, 0x9a, 0x1d,
	0x58, 0xa2, 0x2b, 0x2f, 0x90, 0x43, 0x8e, 0x39, 0x24, 0x97, 0x54, 0x52, 0xc9, 0x25, 0x2f, 0x90,
	0xaa, 0x3c, 0x43, 0x1e, 0x20, 0xb7, 0x5c, 0x73, 0xcc, 0x21, 0x0f, 0x90, 0x9a, 0x9e, 0x59, 0x60,
	0x96, 0x80, 0x64, 0xc6, 0xb7, 0xed, 0x6f, 0x7a, 0x7a, 0x7a, 0x7a, 0x7a, 0xfa, 0x67, 0x16, 0xec,
	0x88, 0x89, 0x8f, 0xc6, 0x49, 0x9f, 0x27, 0xfe, 0x66, 0xc2, 0x63, 0x11, 0x93, 0x62, 0xc4, 0x84,
	0x7b, 0x07, 0xaa, 0xdd, 0x30, 0x1a, 0x76, 0xe3, 0x68, 0x48, 0xae, 0xc2, 0xca, 0xb7, 0xde, 0x78,
	0xca, 0x1c, 0xeb, 0x8e, 0x75, 0xbf, 0x41, 0x15, 0xe1, 0x1e, 0xc2, 0xad, 0xbd, 0x28, 0x38, 0xe1,
	0x5e, 0x94, 0xfa, 0x71, 0x10, 0x46, 0xc3, 0x1e, 0x4b, 0xd3, 0x30, 0x8e, 0x28, 0x7b, 0x31, 0x65,
	0xa9, 0x20, 0x1f, 0x02, 0x78, 0x53, 0x31, 0xea, 0x8b, 0xf8, 0x8c, 0x45, 0x38, 0xb5, 0xde, 0x5e,
	0xdd, 0x8c, 0x98, 0xd8, 0xdc, 0x9e, 0x8a, 0xd1, 0x89, 0x44, 0x69, 0xcd, 0xcb, 0x3e, 0xdd, 0x77,
	0xe0, 0xf6, 0x6b, 0xc4, 0xa5, 0x49, 0x1c, 0xa5, 0xcc, 0xfd, 0xab, 0x05, 0x1b, 0xc7, 0xdc, 0x1f,
	0xb1, 0x54, 0x70, 0x4f, 0xc4, 0x3c, 0x5b, 0xc7, 0x81, 0x8a, 0x17, 0x04, 0x9c, 0xa5, 0xa9, 0xd6,
	0x2f, 0x23, 0x89, 0x0d, 0xc5, 0x34, 0x1c, 0x3a, 0x05, 0x44, 0xe5, 0x27, 0x79, 0x04, 0x0d, 0xdf,
	0x4b, 0xbc, 0xd3, 0x70, 0x1c, 0x8a, 0x90, 0xa5, 0x4e, 0x11, 0xb5, 0x5a, 0x47, 0xad, 0x76, 0x8c,
	0x01, 0x9a, 0x63, 0x23, 0x0f, 0x60, 0x23, 0x1c, 0x46, 0x31, 0x67, 0x92, 0xc7, 0x0f, 0xc5, 0xf9,
	0xce, 0x88, 0xf9, 0x67, 0x4e, 0xe9, 0x8e, 0x75, 0xbf, 0x4a, 0x97, 0x0d, 0xb9, 0xbf, 0xb3, 0xa0,
	0x7c, 0xdc, 0xeb, 0x44, 0x83, 0x98, 0x7c, 0x0a, 0xf5, 0x54, 0xc4, 0xdc, 0x1b, 0xb2, 0x93, 0xf3,
	0x44, 0xd9, 0x70, 0xb5, 0x7d, 0x03, 0x97, 0x54, 0x1c, 0x9b, 0xbd, 0xf9, 0x30, 0x35, 0x79, 0xc9,
	0x3d, 0x28, 0xa7, 0x5b, 0x61, 0x34, 0x88, 0x1d, 0x1b, 0x15, 0x6d, 0xe2, 0xac, 0xde, 0x96, 0x9a,
	0x47, 0xf5, 0xa0, 0xfb, 0x21, 0xd4, 0x0d, 0x11, 0x04, 0xa0, 0xbc, 0xdb, 0xa1, 0x7b, 0x3b, 0x27,
	0xf6, 0x15, 0x52, 0x86, 0x42, 0x6f, 0xcb, 0xb6, 0x24, 0xb6, 0x7f, 0x7c, 0xbc, 0xff, 0xf5, 0x9e,
	0x5d, 0x70, 0xff, 0x64, 0x41, 0x35, 0x93, 0x41, 0x08, 0x94, 0x46, 0x71, 0x2a, 0x50, 0xad, 0x1a,
	0xc5, 0x6f, 0x69, 0xb7, 0x33, 0x76, 0x8e, 0x76, 0xab, 0x51, 0xf9, 0x49, 0xae, 0x43, 0x39, 0x89,
	0xc7, 0xa1, 0x7f, 0x8e, 0x16, 0xab, 0x51, 0x4d, 0x91, 0x5b, 0x50, 0x4b, 0xc3, 0x61, 0xe4, 0x89,
	0x29, 0x67, 0x68, 0x8e, 0x1a, 0x9d, 0x03, 0xe4, 0x6d, 0x00, 0x9f, 0xb3, 0x80, 0x45, 0x22, 0xf4,
	0xc6, 0xce, 0x0a, 0x0e, 0x1b, 0x08, 0x69, 0x41, 0xf5, 0xd5, 0xf6, 0xe4, 0xbb, 0x5d, 0x4f, 0x30,
	0xa7, 0x8c, 0xa3, 0x33, 0xda, 0xfd, 0xad, 0x05, 0xb5, 0x2e, 0x0f, 0x7d, 0x86, 0x5a, 0xba, 0xd0,
	0x48, 0x24, 0xd1, 0x65, 0xfc, 0x59, 0x14, 0x2a, 0x6d, 0x8b, 0x34, 0x87, 0x91, 0xf7, 0xa0, 0x99,
	0x84, 0xaf, 0xd8, 0x38, 0xcd, 0x98, 0x0a, 0xc8, 0x94, 0x07, 0x51, 0xa7, 0xec, 0x68, 0xd5, 0x6e,
	0x9a, 0xd4, 0x40, 0x70, 0x3c, 0x8e, 0xa4, 0x8b, 0x85, 0x91, 0xd0, 0x5b, 0x32, 0x10, 0xf7, 0xd7,
	0x15, 0x68, 0x98, 0x9e, 0x22, 0x4d, 0x70, 0x1a, 0x8a, 0x54, 0xf0, 0x30, 0x1a, 0x3a, 0xd6, 0x9d,
	0xe2, 0xfd, 0x12, 0x9d, 0x03, 0xe4, 0x0e, 0xd4, 0x27, 0x5e, 0x14, 0x48, 0x7f, 0x95, 0xfe, 0x56,
	0xc0, 0x71, 0x13, 0x22, 0xdb, 0x4a, 0x21, 0x3f, 0x73, 0xc8, 0xe2, 0xfd, 0x7a, 0xfb, 0xee, 0x82,
	0x43, 0x6e, 0xee, 0xcc, 0x78, 0xf6, 0x22, 0xc1, 0xcf, 0xa9, 0x31, 0x49, 0xde, 0x80, 0x6f, 0x19,
	0x97, 0x97, 0x45, 0x2b, 0x9c, 0x91, 0xe4, 0x0b, 0xa8, 0xcf, 0x75, 0x4f, 0xf1, 0x08, 0xea, 0xed,
	0xdb, 0x4b, 0xa4, 0xcf, 0x99, 0xa8, 0x39, 0xa3, 0xf5, 0x39, 0xac, 0x5d, 0x58, 0x39, 0xf3, 0x0e,
	0x0b, 0x4d, 0x87, 0xde, 0x31, 0x8b, 0x0f, 0x05, 0xc4, 0x14, 0xf1, 0x59, 0xe1, 0x13, 0xab, 0xf5,
	0x1f, 0x0b, 0xea, 0x86, 0x6c, 0x69, 0xdd, 0x49, 0x18, 0x3d, 0xd7, 0xca, 0x2a, 0x9f, 0x33, 0x10,
	0xf2, 0x1c, 0x9a, 0x5d, 0xc6, 0x77, 0xe6, 0x07, 0x54, 0x40, 0x7b, 0x3c, 0x78, 0xa3, 0xc6, 0x9b,
	0xb9, 0x29, 0xca, 0x3c, 0x79, 0x31, 0xad, 0x10, 0xc8, 0x22, 0xd3, 0x92, 0x9d, 0x7c, 0x6e, 0xee,
	0xa4, 0xde, 0xfe, 0xd1, 0xf2, 0x73, 0x50, 0x32, 0x4c, 0x9b, 0x19, 0x5b, 0xfe, 0x77, 0x01, 0xae,
	0x2d, 0x65, 0x22, 0x3f, 0x81, 0xf2, 0x24, 0x0e, 0xd8, 0x38, 0x45, 0x37, 0xa9, 0xb7, 0xb7, 0x2e,
	0x29, 0x7d, 0xf3, 0x10, 0x67, 0xa9, 0x8d, 0x69, 0x11, 0xad, 0xdf, 0x58, 0xb0, 0x86, 0xf8, 0x9c,
	0x51, 0xde, 0xe5, 0x97, 0x1e, 0x9f, 0xe0, 0x86, 0xaa, 0x14, 0xbf, 0xe5, 0x1d, 0xd3, 0x9e, 0x72,
	0xae, 0x8f, 0x67, 0x46, 0xcb, 0x1b, 0xc3, 0xa7, 0x51, 0xc4, 0x78, 0x76, 0x20, 0xea, 0x72, 0xe7,
	0x41, 0xc9, 0x95, 0xcd, 0xe8, 0x44, 0xcf, 0x52, 0x75, 0xcf, 0x9b, 0x34, 0x0f, 0xb6, 0x38, 0xd4,
	0x0d, 0x35, 0x4d, 0xd3, 0xea, 0x10, 0x72, 0x98, 0x37, 0xed, 0xc7, 0xff, 0xd7, 0xe6, 0xe7, 0x80,
	0x61, 0x6a, 0xf7, 0x6f, 0x45, 0xb0, 0xcd, 0x8c, 0x80, 0xa1, 0xe2, 0x6d, 0x00, 0xa1, 0x93, 0x08,
	0xe3, 0x99, 0x8b, 0xcd, 0x11, 0xf2, 0x18, 0x9a, 0x22, 0xf4, 0xcf, 0x98, 0xe8, 0x27, 0x1e, 0xf7,
	0x26, 0xa9, 0xd6, 0x47, 0xe5, 0x80, 0x13, 0x1c, 0xe9, 0xe2, 0x00, 0x6d, 0x08, 0x83, 0x92, 0xe9,
	0x0c, 0xc3, 0x4d, 0x1f, 0xe3, 0x71, 0xd1, 0x48, 0x67, 0xb3, 0x30, 0x45, 0x6b, 0xc9, 0x2c, 0x62,
	0x19, 0x59, 0xa9, 0x94, 0xcf, 0x4a, 0x17, 0x73, 0xd0, 0xca, 0xe5, 0x72, 0x50, 0x3e, 0x9d, 0x96,
	0xbf, 0x27, 0x9d, 0x92, 0x87, 0x50, 0x1d, 0x79, 0x3c, 0x78, 0xe9, 0x71, 0xe6, 0x54, 0xd0, 0xdd,
	0x1c, 0x64, 0x3e, 0xd0, 0xa0, 0x54, 0x92, 0x4f, 0x3c, 0x21, 0x33, 0xec, 0x8c, 0x93, 0xdc, 0x83,
	0x8a, 0xce, 0x3f, 0xce, 0x1d, 0x9c, 0x54, 0x37, 0xf2, 0x14, 0xcd, 0xc6, 0xc8, 0x17, 0xb0, 0x61,
	0xea, 0xd6, 0xc7, 0x6d, 0xa7, 0xce, 0x5d, 0x9c, 0x72, 0xd1, 0x28, 0xc4, 0x64, 0x45, 0x38, 0x75,
	0x7f, 0x09, 0xb5, 0x99, 0xd6, 0x32, 0x7c, 0xcc, 0x6b, 0x84, 0x06, 0x55, 0x04, 0xb9, 0x0d, 0x90,
	0xaa, 0x0a, 0xa0, 0x1f, 0x06, 0x3a, 0x17, 0xd5, 0x34, 0xd2, 0x09, 0xe4, 0x31, 0xb3, 0x57, 0x49,
	0xc8, 0x71, 0x07, 0x78, 0x1c, 0x45, 0x6a, 0x20, 0xee, 0x7f, 0x4b, 0x50, 0xe9, 0xb1, 0xe1, 0xae,
	0x27, 0x3c, 0x8c, 0x3a, 0x5e, 0x14, 0x0e, 0x58, 0x2a, 0x3a, 0x81, 0x5e, 0xc5, 0x40, 0xb0, 0x4e,
	0x60, 0x2f, 0x74, 0xbe, 0x90, 0x9f, 0x98, 0x15, 0xbd, 0x74, 0x84, 0x72, 0x1b, 0x14, 0xbf, 0xe5,
	0x4d, 0x4a, 0x78, 0x3c, 0x08, 0xc7, 0x2c, 0x3b, 0xd2, 0x19, 0x9d, 0x55, 0x1a, 0x2b, 0xf3, 0x4a,
	0xa3, 0x05, 0xd5, 0x60, 0xaa, 0xb5, 0x93, 0x87, 0xb5, 0x42, 0x67, 0xf4, 0x82, 0x07, 0x54, 0x7e,
	0x88, 0x07, 0x54, 0xbf, 0xcf, 0x03, 0x1e, 0xc0, 0x55, 0xdf, 0x1b, 0xfb, 0xfd, 0x84, 0x71, 0x9f,
	0x25, 0x62, 0xea, 0x8d, 0xfb, 0xb8, 0x27, 0xc0, 0xe8, 0x40, 0xe4, 0x58, 0x77, 0x36, 0x74, 0x20,
	0x77, 0x78, 0xc9, 0xd3, 0x7f, 0x04, 0x8d, 0xc1, 0x74, 0x3c, 0xee, 0x66, 0xc6, 0x50, 0xc7, 0xae,
	0xd4, 0x7f, 0x1e, 0x06, 0x2c, 0xd6, 0x23, 0x34, 0xc7, 0x46, 0x3e, 0x86, 0xa6, 0x49, 0xb7, 0x1d,
	0xf7, 0x75, 0xf3, 0xf2, 0x7c, 0x17, 0x27, 0x6e, 0x39, 0xef, 0x5e, 0x6a, 0xe2, 0x16, 0xd9, 0x06,
	0x92, 0xb2, 0xe1, 0x84, 0x45, 0xfa, 0xae, 0x33, 0xc1, 0x78, 0xea, 0xdc, 0x43, 0xc3, 0x11, 0x55,
	0x4a, 0xb1, 0x61, 0x77, 0x36, 0x42, 0xd7, 0x35, 0xf7, 0x1c, 0x22, 0x9b, 0x40, 0x9e, 0xc6, 0xdc,
	0x67, 0xb3, 0x62, 0x34, 0x94, 0x95, 0xc5, 0xfb, 0xca, 0x84, 0x8b, 0x23, 0xee, 0x16, 0x34, 0x73,
	0x32, 0xa5, 0x27, 0x0d, 0x78, 0xac, 0x62, 0x72, 0x89, 0xe2, 0x37, 0x59, 0x85, 0x82, 0x88, 0xd1,
	0xdd, 0x4a, 0xb4, 0x20, 0x62, 0xf7, 0x1f, 0x2b, 0xd0, 0x30, 0xf7, 0x21, 0x27, 0x45, 0xde, 0x84,
	0x61, 0xd5, 0x57, 0xa3, 0xf8, 0x2d, 0x6f, 0xc9, 0xcb, 0x30, 0x10, 0x23, 0x67, 0x1d, 0xbd, 0x49,
	0x11, 0xb2, 0x30, 0x1b, 0xb1, 0x70, 0x38, 0x12, 0x0e, 0x41, 0x58, 0x53, 0x32, 0xfc, 0x9c, 0x86,
	0x32, 0x2a, 0x32, 0x67, 0x03, 0x07, 0x32, 0x52, 0xba, 0xea, 0x20, 0x49, 0x9d, 0xab, 0x2a, 0xe9,
	0x0d, 0x12, 0x59, 0xdd, 0x96, 0x55, 0x2c, 0x70, 0xae, 0x61, 0x6d, 0xea, 0x2c, 0x18, 0x76, 0xf3,
	0x29, 0x8e, 0x53, 0xcd, 0x27, 0x57, 0x1d, 0x24, 0xe9, 0x2e, 0x8b, 0x9c, 0xeb, 0x28, 0x46, 0x53,
	0x64, 0x0b, 0x2a, 0xfa, 0x4a, 0x38, 0x37, 0x50, 0xd4, 0xcd, 0x45, 0x51, 0xd9, 0x59, 0x65, 0x9c,
	0x52, 0xa1, 0x61, 0x9c, 0x38, 0x0e, 0xaa, 0x29, 0x3f, 0xc9, 0x63, 0xa8, 0xb0, 0x48, 0xc5, 0xef,
	0x9b, 0x28, 0xe6, 0xd6, 0xa2, 0x18, 0x24, 0x76, 0xe2, 0x80, 0xf9, 0x34, 0x63, 0x56, 0xb5, 0xdb,
	0x38, 0xe6, 0xbb, 0x2c, 0x11, 0x23, 0xa7, 0x85, 0x02, 0x0d, 0x84, 0xec, 0x43, 0xc3, 0x1f, 0xf1,
	0x78, 0xe2, 0xa9, 0xed, 0x38, 0x6f, 0xa1, 0xf0, 0x77, 0x17, 0x85, 0xef, 0x20, 0x57, 0x6f, 0x7a,
	0x9a, 0x7a, 0x93, 0x64, 0x1c, 0x46, 0x43, 0x9a, 0x9b, 0x28, 0xad, 0xfb, 0x62, 0xea, 0x61, 0x81,
	0x72, 0x0b, 0x0d, 0x90, 0x91, 0xee, 0x6d, 0x28, 0x6b, 0x1e, 0x80, 0xf2, 0x61, 0x77, 0x6f, 0xff,
	0xa4, 0x67, 0x5f, 0x21, 0x15, 0x28, 0x1e, 0x76, 0x1f, 0xda, 0x96, 0xfb, 0x0d, 0x54, 0xb2, 0x33,
	0xde, 0x80, 0xb5, 0xbd, 0xa3, 0x9d, 0xe3, 0xdd, 0x3d, 0xda, 0xdf, 0xdd, 0x7b, 0xba, 0xfd, 0xec,
	0x6b, 0x59, 0xae, 0xaf, 0x43, 0xf3, 0xa0, 0xfd, 0xf8, 0x61, 0xff, 0xc9, 0x76, 0x6f, 0xef, 0xeb,
	0xce, 0xd1, 0x9e, 0x6d, 0x91, 0x26, 0xd4, 0x10, 0x3a, 0xdc, 0xee, 0x1c, 0xd9, 0x85, 0x19, 0x79,
	0xd0, 0xd9, 0x3f, 0xb0, 0x8b, 0xe4, 0x26, 0x5c, 0x43, 0x72, 0xe7, 0xf8, 0xa8, 0x77, 0x42, 0xb7,
	0x3b, 0x47, 0x7b, 0xbb, 0x6a, 0xa8, 0xe4, 0xb6, 0x01, 0xe6, 0x46, 0x22, 0x55, 0x28, 0x49, 0x46,
	0xfb, 0x8a, 0xfe, 0x7a, 0x64, 0x5b, 0x52, 0xad, 0xe7, 0xdd, 0x4f, 0xec, 0x82, 0xfa, 0xf8, 0xd4,
	0x2e, 0xba, 0x3b, 0xb0, 0xbe, 0xb0, 0x77, 0xb2, 0x0a, 0xb0, 0x73, 0x40, 0x8f, 0x0f, 0xb7, 0xfb,
	0x0f, 0xdb, 0x0f, 0xec, 0x2b, 0x39, 0xba, 0x6d, 0x5b, 0x26, 0xfd, 0xf0, 0xa1, 0x5d, 0x70, 0x5f,
	0xc0, 0xb5, 0xac, 0x8d, 0x63, 0x41, 0x4f, 0x5d, 0x29, 0x8c, 0xc3, 0x36, 0x14, 0xa7, 0x7c, 0x9c,
	0x15, 0x05, 0x53, 0x3e, 0xc6, 0xbe, 0x02, 0xcb, 0x73, 0x1d, 0x7c, 0x35, 0x45, 0x36, 0x61, 0xe3,
	0x42, 0xd8, 0xea, 0xcb, 0x99, 0xaa, 0x3e, 0x59, 0x4f, 0x72, 0x61, 0xeb, 0x19, 0x1f, 0xbb, 0x3f,
	0x83, 0xe6, 0x6c, 0x49, 0x5c, 0xea, 0x31, 0x54, 0xf5, 0x65, 0xce, 0xaa, 0xad, 0x96, 0x4a, 0xf0,
	0xcb, 0x14, 0xa3, 0x33, 0xde, 0xc5, 0x96, 0xd1, 0xfd, 0xbd, 0x05, 0x6b, 0xb3, 0x59, 0x94, 0xa5,
	0xd3, 0xb1, 0xc8, 0x12, 0x86, 0x35, 0x4f, 0x18, 0xd7, 0x61, 0x85, 0x71, 0x1e, 0x73, 0x95, 0xa8,
	0x0e, 0xae, 0x50, 0x45, 0x92, 0xfb, 0x50, 0x0a, 0x3c, 0xe1, 0xe9, 0x7a, 0x81, 0xe4, 0x75, 0x90,
	0x6b, 0x1f, 0x5c, 0xa1, 0xc8, 0x41, 0x3e, 0x80, 0x92, 0xd1, 0xe9, 0x5d, 0x53, 0x91, 0xf7, 0x42,
	0x71, 0x43, 0x91, 0xe5, 0x49, 0x15, 0xca, 0x1c, 0x15, 0x71, 0x3f, 0x83, 0x66, 0xd7, 0x3b, 0x97,
	0xaa, 0x6b, 0xcd, 0x2e, 0x2f, 0xc5, 0xfd, 0x15, 0xac, 0x51, 0x36, 0x0c, 0x53, 0xc1, 0x66, 0xad,
	0xf4, 0x75, 0x28, 0xa7, 0xcc, 0xe7, 0x2c, 0x6b, 0x07, 0x35, 0xb5, 0x50, 0x44, 0x16, 0x8d, 0x22,
	0xf2, 0x87, 0xb5, 0xd4, 0xee, 0x1f, 0x2d, 0x68, 0x1e, 0xc5, 0x22, 0x1c, 0x9c, 0xeb, 0x83, 0x58,
	0xe2, 0x1d, 0xef, 0x43, 0x25, 0x55, 0x29, 0x5c, 0x4b, 0x6d, 0x64, 0x41, 0x1b, 0x4f, 0x2d, 0x1b,
	0x94, 0x6a, 0x0b, 0x2f, 0x3d, 0xeb, 0x04, 0xb8, 0xed, 0x22, 0xd5, 0x94, 0xc4, 0x63, 0xee, 0x8f,
	0x3a, 0x01, 0x06, 0xc7, 0x1a, 0xd5, 0x54, 0x2e, 0x93, 0xaf, 0xe7, 0x33, 0xf9, 0x57, 0xa5, 0x6a,
	0xc1, 0x2e, 0x7e, 0x55, 0xaa, 0xde, 0xb5, 0x5d, 0xf7, 0xef, 0x16, 0xdc, 0xc8, 0x4c, 0xb4, 0xdd,
	0xf9, 0x69, 0xcc, 0xcf, 0xbe, 0xdf, 0x54, 0x17, 0xcd, 0x51, 0xb8, 0x5c, 0x6e, 0x37, 0xcb, 0xb5,
	0xe2, 0xa5, 0xcb, 0x35, 0xf3, 0x5c, 0x4a, 0xf9, 0x73, 0x71, 0x3b, 0x50, 0xdb, 0xee, 0x7c, 0x15,
	0x9f, 0xa2, 0x85, 0xe4, 0x8e, 0xc3, 0x84, 0x8d, 0xc3, 0x88, 0x69, 0x7d, 0x67, 0xb4, 0x6c, 0x51,
	0xb9, 0xda, 0x14, 0x5a, 0x5a, 0xb9, 0xbe, 0x09, 0xb9, 0x3d, 0xa8, 0xab, 0xa3, 0x42, 0x81, 0xe4,
	0xc7, 0x86, 0xe4, 0xfc, 0xbb, 0x4e, 0x86, 0x52, 0x63, 0xe9, 0xf9, 0xe1, 0x14, 0xcc, 0xc3, 0x71,
	0xff, 0x50, 0x80, 0x86, 0x59, 0x6e, 0xcb, 0x46, 0x9a, 0x33, 0x3f, 0x4c, 0x42, 0x16, 0x09, 0x5d,
	0xa4, 0xcd, 0x01, 0x59, 0x0e, 0x0e, 0x3c, 0x9f, 0xf5, 0xe7, 0x3d, 0x44, 0x83, 0xd6, 0x24, 0xf2,
	0x5c, 0x02, 0xe4, 0x26, 0x54, 0x5f, 0x86, 0x51, 0x3f, 0xe1, 0xf1, 0xa9, 0x2e, 0xda, 0x2a, 0x2f,
	0xc3, 0xa8, 0xcb, 0xe3, 0x53, 0x19, 0x4b, 0x66, 0x62, 0xfa, 0xdc, 0x8b, 0x02, 0x55, 0x06, 0xa9,
	0x12, 0x6e, 0x7d, 0x36, 0x44, 0xbd, 0x28, 0xc0, 0x2a, 0x88, 0x40, 0x29, 0x65, 0x2c, 0xd0, 0xc5,
	0x1c, 0x7e, 0x93, 0x0f, 0xc0, 0x9e, 0xd7, 0x96, 0xfd, 0xd3, 0x71, 0xec, 0x9f, 0x61, 0x55, 0xd7,
	0xa0, 0x6b, 0x73, 0xfc, 0x89, 0x84, 0xc9, 0x01, 0xac, 0x1b, 0xac, 0xba, 0xc7, 0x50, 0x15, 0xde,
	0x5b, 0x46, 0x8f, 0xb1, 0x37, 0xe3, 0xd1, 0xdd, 0x86, 0xb1, 0x80, 0x42, 0xdc, 0x0e, 0x10, 0xc5,
	0xdb, 0x63, 0x51, 0xc0, 0xb8, 0x36, 0xd3, 0x5d, 0x68, 0xa4, 0x48, 0xf7, 0xa3, 0x38, 0xf2, 0x99,
	0xee, 0x5e, 0xeb, 0x0a, 0x3b, 0x92, 0xd0, 0x92, 0x20, 0xf6, 0x1d, 0x5c, 0x5f, 0xbe, 0x2c, 0xb9,
	0x07, 0xab, 0x3e, 0x67, 0x4a, 0x59, 0x1e, 0x4f, 0xa3, 0x40, 0x47, 0xb5, 0x66, 0x86, 0x52, 0x09,
	0x92, 0x4f, 0xe1, 0x66, 0x9e, 0x4d, 0x19, 0x41, 0x99, 0x52, 0x2d, 0x74, 0x3d, 0x37, 0x03, 0x8d,
	0x21, 0xed, 0xe9, 0xfe, 0xa5, 0x00, 0x15, 0x1d, 0xa4, 0x16, 0x9b, 0x2f, 0xeb, 0x72, 0xcd, 0x17,
	0xde, 0x36, 0xb9, 0x41, 0xbd, 0x96, 0xa6, 0x96, 0x1b, 0xbb, 0xf8, 0x03, 0x8c, 0x4d, 0x3a, 0x70,
	0x55, 0x6b, 0xa6, 0xad, 0xab, 0x85, 0x95, 0xf0, 0x32, 0xde, 0x30, 0x84, 0x99, 0xa7, 0x41, 0x89,
	0x58, 0x3c, 0xa1, 0x47, 0xb0, 0xca, 0x5e, 0x25, 0xcc, 0x17, 0x2c, 0x50, 0x9d, 0x91, 0x6e, 0xf1,
	0x2e, 0x36, 0x46, 0xcd, 0x8c, 0x0b, 0x21, 0xf7, 0xcf, 0x16, 0xac, 0xee, 0x77, 0x9f, 0xed, 0xc4,
	0x93, 0x64, 0x2a, 0x54, 0x13, 0xb9, 0x0a, 0x85, 0x30, 0xd0, 0x17, 0xb6, 0x10, 0x06, 0xb3, 0xba,
	0xb0, 0x90, 0xaf, 0x0b, 0x27, 0xde, 0x37, 0x31, 0xd7, 0x6d, 0xb9, 0x22, 0x10, 0x0d, 0xa3, 0x98,
	0xe3, 0xd2, 0x12, 0x95, 0x04, 0x79, 0x07, 0xea, 0x13, 0x36, 0x89, 0xf9, 0x79, 0x7f, 0xc0, 0x99,
	0x7a, 0x73, 0x2b, 0x52, 0x50, 0xd0, 0x53, 0xce, 0x98, 0x74, 0x2e, 0xcd, 0x20, 0x62, 0xe1, 0x8d,
	0xd1, 0x6f, 0x8b, 0x54, 0x4f, 0x3a, 0x91, 0x90, 0xfb, 0x2f, 0x0b, 0x36, 0x96, 0x44, 0xa5, 0x37,
	0x86, 0x98, 0x9b, 0x50, 0xc5, 0x67, 0x8b, 0x79, 0x27, 0x57, 0x41, 0xba, 0x13, 0x90, 0x2f, 0xa1,
	0x3a, 0x4c, 0xa6, 0x59, 0x53, 0x2d, 0x6d, 0x7d, 0xef, 0x75, 0x81, 0x6f, 0x73, 0x3f, 0x99, 0x4a,
	0x52, 0x3d, 0x84, 0x54, 0x86, 0x8a, 0x6a, 0x1d, 0x43, 0xc3, 0x1c, 0x58, 0xf2, 0xf4, 0xf0, 0x41,
	0xfe, 0xe9, 0x61, 0x03, 0x17, 0xc8, 0x9b, 0xda, 0x78, 0x56, 0x68, 0xff, 0xd3, 0x82, 0x86, 0x99,
	0x33, 0xc9, 0x13, 0x58, 0xdb, 0x67, 0x22, 0x07, 0x39, 0x0b, 0x99, 0x55, 0x27, 0x86, 0xd6, 0xf2,
	0x9c, 0x4b, 0x7e, 0x01, 0xd7, 0x96, 0x3e, 0x6f, 0x13, 0xf5, 0xd6, 0xf7, 0xa6, 0x97, 0xf4, 0x96,
	0xfb, 0x26, 0x16, 0xf5, 0x3a, 0x4e, 0xde, 0x83, 0x52, 0x57, 0x16, 0x6b, 0xea, 0x89, 0x38, 0x7b,
	0xba, 0x6f, 0xe5, 0xc9, 0x76, 0x17, 0xaa, 0x59, 0x22, 0x23, 0xbb, 0x60, 0x5f, 0x4c, 0x6e, 0x44,
	0x15, 0xda, 0xaf, 0xc9, 0x79, 0x2d, 0x1b, 0x47, 0x8d, 0x54, 0xf0, 0xc0, 0x6a, 0x1f, 0x01, 0x9c,
	0xcc, 0x1f, 0x57, 0xbe, 0x04, 0x92, 0x4d, 0x36, 0xd0, 0xab, 0x39, 0xa9, 0x99, 0x34, 0x62, 0x48,
	0xd3, 0x35, 0xc0, 0x03, 0xeb, 0x49, 0xe5, 0xe7, 0x2b, 0x9b, 0x1f, 0x45, 0x4c, 0x9c, 0x96, 0xf1,
	0x67, 0xc4, 0xd6, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xde, 0x6a, 0xc1, 0x8f, 0xa0, 0x18, 0x00,
	0x00,
}
